Updates for U10
Esri/maps-app-dotnet pull request #69
Opened 2021-01-23 07:36 UTC by nCastle1

2021-01-27 20:28 UTC, esreli requested changes
This PR generally looks good. I'm trusting the app version has been updated to `1.0.9` in all locations, ditto update min SDK Android (23) & iOS (13.0). I have one general question.
What are all of the changes contained by `src/MapsApp.Android/Resources/Resource.Designer.cs`? Were these manual or system derived changes?

---

With the rollout of the new site, there are a number of broken links.

### `README`

- Line `77` - `[new application](https://developers.arcgis.com/applications/new)`
- Line `125` - `[License your app](https://developers.arcgis.com/net/latest/wpf/guide/license-your-app.htm)`

### `docs/README`

- Section: Place search & geocoding - `[here](https://developers.arcgis.com/net/latest/wpf/guide/loadable-pattern.htm)`
- Section: Place search & geocoding - `[Geocoding](https://developers.arcgis.com/net/latest/wpf/guide/search-for-places-geocoding-.htm)`
- Section: Authentication - `[Go here](https://developers.arcgis.com/net/latest/wpf/guide/use-the-authentication-manager.htm)`

2021-01-27 20:28 UTC, esreli commented on RELEASE.md
> +- Removes support for iOS 12.
```suggestion
- Deprecate support for iOS 12.
```

2021-02-19 05:34 UTC, nCastle1 commented
Resources.Designer.cs is a generated file.

2021-02-19 06:24 UTC, nCastle1 commented
App has been fully tested on all platforms, everything working as expected.

2021-02-19 18:27 UTC, esreli approved these changes
One link fix and one pedantic link fix ;) LGTM!

2021-02-19 18:27 UTC, esreli commented on README.md
> +2. Create a [new application](https://developers.arcgis.com/applications).
```suggestion
2. Create a [new application](https://developers.arcgis.com/applications/).
```

2021-02-19 18:27 UTC, esreli commented on README.md
> +For information about licensing your deployed app, see [License your app](https://developers.arcgis.com/applications).
```suggestion
For information about licensing your deployed app, see [License your app](https://developers.arcgis.com/ios/license-and-deployment/license/).
```

2021-02-21 21:51 UTC, merged